### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by obregonia1**
~~I found and fixed one exception message that started with lower case letter.~~

I added "`" to terminator to emphasis it is an argument name.

### CODE REVIEW

**Comment by okuramasafumi** [comment]
Thanks for the PR! This `terminator` is not just a name but an argument name, so I think it should be kept as snake_case. Or we should add "`" to it. What do you think?

**Comment by obregonia1** [comment]
That makes sense.
I think it is easier for the reader to understand this message by adding "`".
I'll revise it if you agree.

**Comment by okuramasafumi** [comment]
@obregonia1 Thank you could you revise it?

**Comment by okuramasafumi** [comment]
Thank you!

**Pull request merged**
